### ISSUE TITLE
Panic in controller in baseSessionRequestContext.getTerminatorSession

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#1255]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x12f9e3f]
goroutine 6574 [running]:
github.com/openziti/edge/controller/handler_edge_ctrl.(*baseSessionRequestContext).getTerminatorSession(0xc001da30e0, 0xc00d117500, 0x1b0b8e0, 0xc006c6f180, 0x0, 0x0, 0x1b0f3b8, 0xc00d1176c0, 0x0)
         /home/runner/go/pkg/mod/github.com/openziti/edge@v0.20.60/controller/handler_edge_ctrl/common.go:356 +0x49f
github.com/openziti/edge/controller/handler_edge_ctrl.(*baseSessionRequestContext).validateTerminatorIdentity(0xc001da30e0, 0xc00d117500, 0x1b0b8e0, 0xc006c6f180, 0xc009e9c2c8, 0x4)
        /home/runner/go/pkg/mod/github.com/openziti/edge@v0.20.60/controller/handler_edge_ctrl/common.go:303 +0x6f
github.com/openziti/edge/controller/handler_edge_ctrl.(*createTerminatorHandler).CreateTerminator.func1(0xc00d117500, 0x1, 0xc00d117500)
        /home/runner/go/pkg/mod/github.com/openziti/edge@v0.20.60/controller/handler_edge_ctrl/create_terminator.go:116 +0x1a8
go.etcd.io/bbolt.(*DB).Update(0xc0000e9200, 0xc002c31e00, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/openziti/bbolt@v1.3.6-0.20210317142109-547da822475e/db.go:706 +0xa6
github.com/openziti/fabric/controller/db.(*Db).Update(0xc000010040, 0xc002c31e00, 0xc00024ec60, 0x7fa6b41a1c60)
        /home/runner/go/pkg/mod/github.com/openziti/fabric@v0.16.105/controller/db/db.go:65 +0x38
github.com/openziti/edge/controller/handler_edge_ctrl.(*createTerminatorHandler).CreateTerminator(0xc001e5e678, 0xc001da30e0)
        /home/runner/go/pkg/mod/github.com/openziti/edge@v0.20.60/controller/handler_edge_ctrl/create_terminator.go:108 +0x7b3
created by github.com/openziti/edge/controller/handler_edge_ctrl.(*createTerminatorHandler).HandleReceive
        /home/runner/go/pkg/mod/github.com/openziti/edge@v0.20.60/controller/handler_edge_ctrl/create_terminator.go:67 +0x305
```

**Comment by plorenz** [comment]
Duplicate of #1187
