### ISSUE TITLE
go-events dependency is not thread-safe

### ISSUE THREAD

**Issue by plorenz** [openziti/edge#328]
```
fatal error: concurrent map read and map write

goroutine 2929 [running]:
runtime.throw(0xf7c620, 0x21)
        /home/plorenz/.gvm/gos/go1.14.7/src/runtime/panic.go:1116 +0x72 fp=0xc001757c60 sp=0xc001757c30 pc=0x438c82
runtime.mapaccess1_faststr(0xe453a0, 0xc0003aa360, 0xf6d2b3, 0x13, 0x10)
        /home/plorenz/.gvm/gos/go1.14.7/src/runtime/map_faststr.go:21 +0x43c fp=0xc001757cd0 sp=0xc001757c60 pc=0x41717c
github.com/kataras/go-events.(*emmiter).Emit(0xc0003ddc60, 0xf6d2b3, 0x13, 0xc00174a260, 0x1, 0x1)
        /home/plorenz/work/nf/build/pkg/mod/github.com/kataras/go-events@v0.0.3-0.20170604004442-17d67be645c3/events.go:148 +0x5c fp=0xc001757d20 sp=0xc001757cd0 pc=0xaba60c
github.com/openziti/edge/gateway/internal/fabric.(*StateManagerImpl).AddSession(0xc000136360, 0xc0015c1480)
        /home/plorenz/work/nf/build/pkg/mod/github.com/openziti/edge@v0.16.25/gateway/internal/fabric/manager.go:149 +0x3ad fp=0xc001757e50 sp=0xc001757d20 pc=0xd0604d
github.com/openziti/edge/gateway/handler_edge_ctrl.(*sessionAddedHandler).HandleReceive.func1(0xc0019404b0, 0xc0003b01e0)
        /home/plorenz/work/nf/build/pkg/mod/github.com/openziti/edge@v0.16.25/gateway/handler_edge_ctrl/sessionAdded.go:48 +0x1af fp=0xc001757fd0 sp=0xc001757e50 pc=0xd0bbff
runtime.goexit()
        /home/plorenz/.gvm/gos/go1.14.7/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc001757fd8 sp=0xc001757fd0 pc=0x4699f1
created by github.com/openziti/edge/gateway/handler_edge_ctrl.(*sessionAddedHandler).HandleReceive
        /home/plorenz/work/nf/build/pkg/mod/github.com/openziti/edge@v0.16.25/gateway/handler_edge_ctrl/sessionAdded.go:43 +0x49
```

**Comment by plorenz** [comment]
go-events updated with fix
